server:
  port: 8000
  ssl:
    enabled: false
spring:
  config:
    name: redis
    location: classpath:/,classpath:/config/,file:./,file:./config/
  profiles:
    active: secret, redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    keyspace-events: expired

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springfox:
  documentation:
    swagger:
      use-model-v3: false

